// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6sIRD3d8soA3TAw3XTSE5IJn7XhuBXAU',
    appId: '1:509258776571:web:467726b4adae814eaad55e',
    messagingSenderId: '509258776571',
    projectId: 'mobile-2-6df82',
    authDomain: 'mobile-2-6df82.firebaseapp.com',
    storageBucket: 'mobile-2-6df82.firebasestorage.app',
    measurementId: 'G-678JKTE7VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgSqcbMzRU8JOolyyboNB7bUxVIVktmvc',
    appId: '1:509258776571:android:af753f27116710aaaad55e',
    messagingSenderId: '509258776571',
    projectId: 'mobile-2-6df82',
    storageBucket: 'mobile-2-6df82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDusWPX_V2xzvwGUZ5cRhjsbwt-Ig1TZfQ',
    appId: '1:509258776571:ios:b9fcc935d0e2b4ceaad55e',
    messagingSenderId: '509258776571',
    projectId: 'mobile-2-6df82',
    storageBucket: 'mobile-2-6df82.firebasestorage.app',
    iosBundleId: 'com.example.vitacareFlutter',
  );
}
